// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth.post').default>>>>
    }
    '/api/clients': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/clients.get').default>>>>
    }
    '/api/lawyers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lawyers.get').default>>>>
    }
    '/api/provided-services': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/provided-services.get').default>>>>
    }
    '/api/requests': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/requests.get').default>>>>
    }
    '/api/services': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/services.get').default>>>>
    }
    '/api/test-db': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test-db').default>>>>
    }
  }
}
export {}